project:
  type: website

format:
  html:
    theme: cosmo
    toc: true


website:
  title: Yemen Energy Team Analytics
  site-url:  https://seloud-wb.github.io/yemen_energy_analytics_website/  # <— makes the title/logo link to Home
  navbar:
    background: dark
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "YEEAP II"
        menu:
          - text: "Tracker"
            href: pages/yeeap_mfi.qmd
          - text: "Documentation"
            href: pages/yeeap_documentation.qmd
