project:
  type: website

format:
  html:
    theme: cosmo
    toc: true


website:
  title: Yemen Energy Team Analytics
  page-navigation: true       # <— enable next/previous page links
  navbar:
    background: dark
    search: true
    left:
      - text: "Home"
        href: pages/index.qmd
      - text: "YEEAP II"
        menu:
          - text: "Tracker"
            href: pages/yeeap_mfi.qmd
          - text: "Documentation"
            href: pages/yeeap_documentation.qmd
